export const categories={hair:{name:'Haircuts',singular:'haircut',intro:'Good hair starts with a conversation. Find your signature cut, and we’ll make it yours.',label:'Precision. Texture. Personality.',image:'skin-fade'},beard:{name:'Beard grooming',singular:'beard service',intro:'Clean lines, considered shape and a proper finish. A little attention makes all the difference.',label:'A sharper kind of detail.',image:'beard-sculpt'},skin:{name:'Skin care',singular:'skin treatment',intro:'Take a moment for yourself. Thoughtful face treatments to leave you feeling fresh and restored.',label:'Refresh. Reset. Recharge.',image:'mud-mask'}};
export const services=[
{id:'skin-fade',category:'hair',name:'Skin Fade',minutes:45,price:25,tag:'The signature',description:'A seamless blend from bare skin to a textured top. Sharp around the edges, clean through the sides, and tailored to your natural growth.'},
{id:'taper-fade',category:'hair',name:'Taper Fade',minutes:40,price:23,tag:'Effortlessly clean',description:'A subtle fade around the temples and neckline, with length kept where it matters. A versatile, understated finish that grows out naturally and neatly.'},
{id:'textured-crop',category:'hair',name:'Textured Crop',minutes:35,price:23,tag:'Modern texture',description:'A short, textured top with a defined fringe and neatly blended sides. Easy to style each morning, with plenty of movement and a contemporary edge.'},
{id:'classic-scissor',category:'hair',name:'Classic Scissor Cut',minutes:35,price:22,tag:'Always in style',description:'Careful scissor work creates a balanced shape with a softer, natural finish. Perfect for keeping a little length and a style that feels entirely yours.'},
{id:'buzz-cut',category:'hair',name:'Buzz Cut',minutes:20,price:16,tag:'Less is more',description:'A crisp, even clipper cut with a neatly finished neckline and edges. Minimal maintenance, maximum confidence, and a length chosen to suit your features.'},
{id:'pompadour',category:'hair',name:'Pompadour',minutes:45,price:28,tag:'A modern classic',description:'Volume through the front, swept back with purpose and balanced by tidy sides. A confident classic, finished with a blow-dry and the right styling product.'},
{id:'curly-fade',category:'hair',name:'Curly Fade',minutes:45,price:27,tag:'Own your texture',description:'Defined curls on top meet a clean, gradual fade at the sides. We work with your natural texture to create shape, balance and effortless movement.'},
{id:'custom-cut',category:'hair',name:'Custom Haircut',minutes:60,price:25,maxPrice:40,tag:'Your vision. Our craft.',description:'Something different in mind? Bring a reference or talk us through your idea. We’ll plan a personal cut together and agree the price before we begin.'},
{id:'beard-sculpt',category:'beard',name:'Beard Trim & Shape',minutes:20,price:12,tag:'Clean definition',description:'A considered trim to balance your beard, sharpen the outline and tidy the neckline. Finished with conditioning beard oil for a clean, comfortable everyday look.'},
{id:'beard-fade',category:'beard',name:'Beard Fade',minutes:25,price:15,tag:'Seamlessly blended',description:'A smooth transition from the sideburns into a fuller beard, with precise cheek and neck lines. A polished shape that brings your whole look together beautifully.'},
{id:'hot-towel-shave',category:'beard',name:'Turkish Hot Towel Shave',minutes:35,price:22,tag:'The traditional ritual',description:'Unwind with a warm towel, rich shaving lather and a careful straight-razor finish. A traditional Turkish ritual, completed with soothing aftercare for freshly shaved skin.'},
{id:'royal-beard',category:'beard',name:'Royal Beard Ritual',minutes:40,price:25,tag:'A little extra care',description:'A full beard reshape with detailed razor work, a comforting hot towel and nourishing beard oil. Extra time and attention for a thoroughly considered, well-groomed finish.'},
{id:'deep-cleanse',category:'skin',name:'Deep Cleanse',minutes:20,price:12,tag:'A fresh beginning',description:'A gentle cleanse to wash away the day, followed by a warm towel and light moisturiser. A simple refresh that leaves your face feeling clean and comfortable.'},
{id:'charcoal-mask',category:'skin',name:'Charcoal Face Mask',minutes:25,price:15,tag:'The clean-slate treatment',description:'A cleansing charcoal mask, carefully applied after a warm facial cleanse. Take a quiet moment while it settles, then enjoy a fresh rinse and moisturising finish.'},
{id:'mud-mask',category:'skin',name:'Mineral Mud Mask',minutes:40,price:22,tag:'Slow down. Reset.',description:'A mineral-rich mud mask paired with a gentle cleanse and a relaxing facial massage. A slower, soothing treatment, finished with a warm towel and light hydration.'},
{id:'facial-steam',category:'skin',name:'Facial Steam Ritual',minutes:20,price:12,tag:'Breathe it in',description:'Gentle warm steam follows a careful cleanse, giving you a moment to unwind in the chair. Finished with a cool towel and moisturiser for a refreshed feel.'},
{id:'facial-scrub',category:'skin',name:'Exfoliating Face Scrub',minutes:25,price:15,tag:'Smooth things over',description:'A gentle facial scrub lifts away surface build-up, followed by a relaxing warm towel. We finish with light moisturiser to leave your skin feeling smooth and refreshed.'},
{id:'golden-facial',category:'skin',name:'Signature Gold Facial',minutes:45,price:30,tag:'The full experience',description:'Our most indulgent skin ritual combines cleansing, gentle exfoliation and a gold-coloured mask. Enjoy a relaxing facial massage before a warm towel and a nourishing final finish.'}
];
export const barbers=[{id:'sam',name:'Sam Cutz',initials:'SC',role:'Founder & barber',text:'Precision fades. Traditional craft. A personal touch.'},{id:'ahmed',name:'Ahmed Tariq',initials:'AT',role:'Barber',text:'Fresh perspectives. Clean details. Your kind of style.'}];
export const money=s=>s.maxPrice?`£${s.price}–£${s.maxPrice}`:`£${s.price}`;
export const duration=m=>m>=60?`${Math.floor(m/60)}h${m%60?` ${m%60}min`:''}`:`${m} min`;
export const timeLabel=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
export function londonNow(now=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,minutes:Number(p.hour)*60+Number(p.minute)};}
export function availableSlots(date,total,now=new Date()){if(!date||total<=0)return[];const current=londonNow(now);if(date<current.date)return[];const sunday=new Date(date+'T12:00:00Z').getUTCDay()===0;const open=sunday?600:540,close=sunday?960:1140;const slots=[];for(let start=open;start+total<=close;start+=30){if(date===current.date&&start<current.minutes+30)continue;slots.push({start,end:start+total,label:`${timeLabel(start)} – ${timeLabel(start+total)}`});}return slots;}
